import { useState, useEffect } from "react";
import { useLocale } from "../context/LocaleContext";
import LanguageToggle from "./LanguageToggle";
import { Link, NavLink } from "react-router-dom";
import { Button } from "./ui/button";
import { Menu, X } from "lucide-react";
import logoVFL from "../assets/LOGO2-fotor-bg-remover-2026011719450.webp";

const navLinks = [
  { path: "/services", key: "services" },
    { path: "/about",    key: "about"    },
      { path: "/contact",  key: "contact"  },
        { path: "/store",    key: "store"    },
          { path: "/blog",     key: "blog"     },
          ];

          // ─── Hook: detecta si el fondo bajo el nav es oscuro o claro ─────────────────
          function useNavDark() {
            const [dark, setDark] = useState(true); // default dark (mayoría de heroes)

              useEffect(() => {
                  const detect = () => {
                        // Muestreamos un punto debajo del nav (~90px desde arriba)
                              const x = Math.round(window.innerWidth / 2);
                                    const y = 90;
                                          const el = document.elementFromPoint(x, y);
                                                if (!el) return;

                                                      // 1. Primero busca atributo data-nav-theme en ancestros (override manual)
                                                            let node = el;
                                                                  while (node && node !== document.body) {
                                                                          const theme = node.getAttribute?.("data-nav-theme");
                                                                                  if (theme === "dark")  { setDark(true);  return; }
                                                                                          if (theme === "light") { setDark(false); return; }
                                                                                                  node = node.parentElement;
                                                                                                        }

                                                                                                              // 2. Busca el primer background-color sólido en el árbol DOM
                                                                                                                    node = el;
                                                                                                                          while (node && node !== document.body) {
                                                                                                                                  const bg = window.getComputedStyle(node).backgroundColor;
                                                                                                                                          if (!bg || bg === "rgba(0, 0, 0, 0)" || bg === "transparent") {
                                                                                                                                                    node = node.parentElement;
                                                                                                                                                              continue;
                                                                                                                                                                      }
                                                                                                                                                                              const nums = bg.match(/[\d.]+/g);
                                                                                                                                                                                      if (!nums || nums.length < 3) { node = node.parentElement; continue; }
                                                                                                                                                                                              const [r, g, b, a = 1] = nums.map(Number);
                                                                                                                                                                                                      if (a < 0.15) { node = node.parentElement; continue; } // ignora casi-transparentes

                                                                                                                                                                                                              // Luminancia perceptual: < 128 → oscuro → letras blancas
                                                                                                                                                                                                                      const lum = 0.299 * r + 0.587 * g + 0.114 * b;
                                                                                                                                                                                                                              setDark(lum < 128);
                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                  // 3. Fallback basado en scroll: si estamos arriba, asumir hero oscuro
                                                                                                                                                                                                                                                        setDark(window.scrollY < 100);
                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                detect();
                                                                                                                                                                                                                                                                    window.addEventListener("scroll", detect, { passive: true });
                                                                                                                                                                                                                                                                        window.addEventListener("resize", detect, { passive: true });

                                                                                                                                                                                                                                                                            // Observa cambios de DOM (cambios de ruta SPA)
                                                                                                                                                                                                                                                                                const mo = new MutationObserver(detect);
                                                                                                                                                                                                                                                                                    mo.observe(document.body, { childList: true, subtree: true });

                                                                                                                                                                                                                                                                                        return () => {
                                                                                                                                                                                                                                                                                              window.removeEventListener("scroll", detect);
                                                                                                                                                                                                                                                                                                    window.removeEventListener("resize", detect);
                                                                                                                                                                                                                                                                                                          mo.disconnect();
                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                }, []);

                                                                                                                                                                                                                                                                                                                  return dark;
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                  // ─── Component ────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                  export default function PublicNav({ dark: forceDark }) {
                                                                                                                                                                                                                                                                                                                    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
                                                                                                                                                                                                                                                                                                                      const { t } = useLocale();
                                                                                                                                                                                                                                                                                                                        const customerToken = localStorage.getItem("customer_token");

                                                                                                                                                                                                                                                                                                                          // Si dark se pasa como prop → respetarlo; si no → detectar automáticamente
                                                                                                                                                                                                                                                                                                                            const autoDark = useNavDark();
                                                                                                                                                                                                                                                                                                                              const dark = forceDark !== undefined ? forceDark : autoDark;

                                                                                                                                                                                                                                                                                                                                const navLabel = {
                                                                                                                                                                                                                                                                                                                                    services: t("Services", "Servicios"),
                                                                                                                                                                                                                                                                                                                                        about:    t("About",    "Nosotros"),
                                                                                                                                                                                                                                                                                                                                            contact:  t("Contact",  "Contacto"),
                                                                                                                                                                                                                                                                                                                                                store:    t("Store",    "Tienda"),
                                                                                                                                                                                                                                                                                                                                                    blog:     t("Blog",     "Blog"),
                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                        // Clases que cambian según el fondo detectado
                                                                                                                                                                                                                                                                                                                                                          const linkBase = "font-medium transition-all duration-200 hover:scale-105";
const linkCls  = `${linkBase} text-white hover:text-white drop-shadow-[0_1px_3px_rgba(0,0,0,0.8)]`;
const activeCls = "!text-white underline underline-offset-4";
const burgerCls = "text-white drop-shadow-[0_1px_3px_rgba(0,0,0,0.8)]";
                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                              <nav className="absolute top-0 left-0 right-0 z-50 py-4 bg-transparent">
                                                                                                                                                                                                                                                                                                                                                                                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between">

                                                                                                                                                                                                                                                                                                                                                                                            {/* Logo */}
                                                                                                                                                                                                                                                                                                                                                                                                    <Link to="/" className="group">
                                                                                                                                                                                                                                                                                                                                                                                                              <img
                                                                                                                                                                                                                                                                                                                                                                                                                          src={logoVFL}
                                                                                                                                                                                                                                                                                                                                                                                                                                      alt="Ventura Fresh Laundry"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="h-28 md:h-36 lg:h-40 w-auto object-contain transition-transform duration-200 group-hover:scale-105"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onError={(e) => { e.currentTarget.style.display = "none"; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Desktop */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="hidden md:flex items-center gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {navLinks.map((link, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <NavLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={link.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  to={link.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={({ isActive }) => `${linkCls} ${isActive ? activeCls : ""}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ transitionDelay: `${idx * 0.04}s` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {navLabel[link.key]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to={customerToken ? "/account" : "/account/login"} className={linkCls}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {t("Account", "Cuenta")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/schedule-pickup">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button className="bg-sky-500 hover:bg-sky-600 text-white rounded-full px-6 py-2.5 transition-all duration-150 hover:scale-105 shadow-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {t("SCHEDULE PICK-UP", "PROGRAMAR RECOLECCIÓN")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <LanguageToggle className="ml-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Mobile burger */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setMobileMenuOpen(v => !v)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`md:hidden p-2 transition-colors duration-200 ${burgerCls}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aria-label="Toggle menu"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {mobileMenuOpen ? <X className="h-7 w-7" /> : <Menu className="h-7 w-7" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Mobile panel — siempre oscuro para legibilidad */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {mobileMenuOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="md:hidden mt-4 px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-2xl p-4 bg-slate-900/90 border border-white/10 backdrop-blur-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-col gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {navLinks.map(link => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <NavLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={link.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to={link.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setMobileMenuOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={({ isActive }) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `font-medium py-2 transition-colors duration-150 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isActive ? "text-white" : "text-white/70 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {navLabel[link.key]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to={customerToken ? "/account" : "/account/login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setMobileMenuOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="font-medium py-2 text-white/70 hover:text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {t("Account", "Cuenta")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link to="/schedule-pickup" onClick={() => setMobileMenuOpen(false)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button className="bg-sky-500 hover:bg-sky-600 text-white rounded-full w-full mt-2 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {t("SCHEDULE PICK-UP", "PROGRAMAR RECOLECCIÓN")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-center pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <LanguageToggle />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }